### ISSUE TITLE
Initialize Project Structure

### ISSUE THREAD

**Issue by webcrumbs-community** [webcrumbs-community/webcrumbs#1]
Set up the initial project files and folders, including package.json, and initial codebase.

**Comment by trdxlucifer** [comment]
how can i do it tell me how can i contribute to this project?

**Comment by webcrumbs-community** [comment]
Hey @trdxlucifer! Glad to have you with us.

It would mean a lot if you could give our project a 🌟, helping our community flourish.

During this initial phase, we're on the lookout for enthusiasts to come together. Share it with others or bring in some friends to the mix. Our goal? Reach a 100 members to truly establish the potential of our project.

**Briefly, our project focuses on:**
	- admin panel's frontend (nextjs)
	- third party plugin dynamics (webpack)
	- a drag and drop feature for web design (?)

We'll dive deeper as we progress. Naturally, as we delve into these key areas, other minor issues will come to light.

We're in the process of figuring out the best options for the drag and drop feature. It'd be great to explore existing solutions, get insights on the tech behind them, and see what's open source.

Here's to a great journey ahead!

**Comment by trdxlucifer** [comment]
i would like to be a part of your team . 
how can i do my contribution tell me i am happy to contribute

**Comment by webcrumbs-community** [comment]
That's great! Tell me what do you prefer doing or what are the areas you feel you can contribute the most? For instance, we still need to put together the project website to be at WebCrumbs.org. We also need to research drag and drops alternatives, as I mentioned. But I'd love for you to do what you feel you can do best

**Comment by webcrumbs-community** [comment]
Contributing to the discussions can also be a first great step, while we still do not have much code.

**Comment by trdxlucifer** [comment]
i love to do front end development work i have skills of React

**Comment by webcrumbs-community** [comment]
That's great my friend. Would you like to begin the frontend of WebCrumbs.org? Feel free to PR something very small to begin this and we grow from there.

**Comment by webcrumbs-community** [comment]
Done
