### ISSUE TITLE
Help us spread the crumbs on Product Hunt ❤️

### ISSUE THREAD

**Issue by webcrumbs-community** [webcrumbs-community/webcrumbs#105]
Calling out our stargazers!

We've made our first sprinkle on the vast internet plains with a soft launch of WebCrumbs on [Product Hunt](https://www.producthunt.com/posts/webcrumbs). Though a smaller step, it's a significant stride towards our big relaunch coming soon. Your upvotes can help us gather more momentum and reach out to a broader community who could benefit from our one-click plugin solution. 

Here’s how you can help:

1. Visit our [Product Hunt page](https://www.producthunt.com/posts/webcrumbs).
2. Give us an upvote if you like what we are baking here. 
3. Spread the word among your networks, every share counts!
4. Share your thoughts or feedback, it’s invaluable for our upcoming relaunch.

Your support now is a huge leap for WebCrumbs' journey. Let's make web development a piece of cake together!

For our relaunch, we have many more flavors (features) in store that will make web development even more delightful and less chore-like. You're welcome to joint the conversation on our GitHub discussions to know more and contribute your ideas. 

If you have any suggestions or run into any issues while upvoting, feel free to reach out. 
Your feedback is the yeast that makes our community rise.

Let’s keep baking a better web. Stay tuned for our relaunch, and we promise, the best crumbs are yet to come!

Happy crumbing!

**Comment by webcrumbs-community** [comment]
@ezequiel-faj @bereznjak @jsimples @felipebarcellosmachado @jmagoga @vibatistella @rnas @ggschuler @tonyAlgara @khairnsaa

**Comment by webcrumbs-community** [comment]
@diomed @AJBrownson @F1nnD3v @alykhan @tdlm @hieuvominh @Edward-Kabue @LuizDMM @atommediabw @NguyenHaiNam24082000

**Comment by webcrumbs-community** [comment]
@ezequiel-faj @bereznjak @jsimples @felipebarcellosmachado @jmagoga @vibatistella @rnas @ggschuler @tonyAlgara @khairnsaa @diomed @AJBrownson @F1nnD3v @alykhan @tdlm @hieuvominh @Edward-Kabue @LuizDMM @atommediabw @NguyenHaiNam24082000 @ranjithkumar8352 @mnkhod @yessur3808 @pmioduszewski @Subtonics @tylerbishopdev @0xMohamed @b4u7 @vejin @petricf96 @ofjake @BADtochka @simonhlee97 @mamunahmed-m360ict @DeluxeOwl @moadel321 @abymoner @Niketanjha @jujuck @chasebenji @SamirMahmudzade @hasniw @atrain42 @TMuthu @alexbrown40 @atomio-eth @neelhabib @anthonyespirat @Johnkat-Mj @Anam0927 @TurniXXD @nylonW @dominicOT @SahilPanhotra @elatfy @deyvtech @tjmakande @CodeStix @PPWPS @evelinabe @godkingjay @Ashok-Kumar-dharanikota @commodus @trdxlucifer @Kayden1412 @melsheikh92 @link89 @djibe @Leetcore @DhairyaMajmudar @Yukitaori @akshbswas98 @entredevs-xyz @shreykoradia @MrSaikatS @krabbi @LucasArthur94 @Moaaz-coder @xare @wahyuandriyanto @vouneo @leonardomelom @fauzie811 @rasidagac @diazmateus @SBigz @dgmagno @robialisandi @cr34turest @byrochtar @ckelwin @ZakariaRchouk @verghese96 @cris-kiri @SKirill-develop @1hakann @dansasser @Nowaxial @DaveKobrin @ulyssear

**Comment by webcrumbs-community** [comment]
@TurniXXD @nylonW @dominicOT @SahilPanhotra @elatfy @deyvtech @tjmakande @CodeStix @PPWPS @evelinabe @godkingjay @Ashok-Kumar-dharanikota @commodus @trdxlucifer @Kayden1412 @melsheikh92 @link89 @djibe @Leetcore @DhairyaMajmudar @Yukitaori @akshbswas98 @entredevs-xyz @shreykoradia @MrSaikatS @krabbi @LucasArthur94 @Moaaz-coder @xare @wahyuandriyanto @vouneo @leonardomelom @fauzie811 @rasidagac @diazmateus @SBigz @dgmagno @robialisandi @cr34turest @byrochtar @ckelwin @ZakariaRchouk @verghese96 @cris-kiri @SKirill-develop @1hakann @dansasser @Nowaxial @DaveKobrin @ulyssear

**Comment by webcrumbs-community** [comment]
![Product](https://s3.amazonaws.com/elpha-imgs/pictures/18610cf82a62c749b0231b3c1cf6d7562895d31e.?1594142546)

**Comment by webcrumbs-community** [comment]
> As this is an open-source project. Why don't we start building in public on Twitter? 

You're absolutely right... This is long overdue. I'll create it and let you know!
It would be good to have help in managing these accounts 😅

**Comment by diomed** [comment]
usually people make discord. lots of devs are having discord communities. 
btw if WebCrumbs is in the making (unreleased) - why do you present it on ProductHunt, and if it's released why does it still say it's unreleased.

I still dont see what exactly webcrumbs is. 
either i'm stupid or something, but where is demo of your product?

**Comment by webcrumbs-community** [comment]
Hey @diomed,

Thanks for taking the time to check out WebCrumbs. You’re right about Discord; we’re in the process of setting up a community there. You're welcome to check. https://discord.gg/ymVgdPe6rK

As for the ProductHunt situation, you caught me—I goofed. I had scheduled the launch for October 30th and it slipped my mind. But, hey, it’s out there now, so might as well make the most of it.

I totally get why you’re a bit puzzled about what WebCrumbs is. We’re working on a demo to make things crystal clear. Should be up and running soon!

Cheers!

**Comment by webcrumbs-community** [comment]
> Yeah, I am also confused as to what it is. React has a huge community so I would get the word out there as fast as possible to see how the community responds to the idea. You wouldn't want to do all this work if there's a possibility, in the end, people don't find it useful. Better to get a demo out asap

Hey there,

You're spot on about the React community and the importance of testing the waters early. We're hustling to get that demo out, but in the meantime, you can take a peek at the image in the README.md and the description on our GitHub page to get a better sense of what WebCrumbs is about.

Still scratching your head? I'm all ears for suggestions.

By the way, you got any tips on how we can better engage the community? Always open to learning from folks who've been around the block.

Cheers!
