### ISSUE TITLE
Add Finland to the flags

### ISSUE THREAD

**Issue by webcrumbs-community** [webcrumbs-community/webcrumbs#121]

**Comment by dew-dr0p** [comment]
What can we do here?
I'd love to help out, more description needed.

**Comment by webcrumbs-community** [comment]
That would be great! There are two files in the main directory starting with COUNTRIES...svg. We have to find an svg of a rounded flag for finland, convert to base64, and add to the right alphabetical place there making the adjustments to the other flags of that line. Let me know if you're up to it. Cheers!

**Comment by dew-dr0p** [comment]
Yh could get that worked on. Let me get to it right away

**Comment by dew-dr0p** [comment]
@webcrumbs-community I just raised a pull request

**Comment by webcrumbs-community** [comment]
That was fast! I'm not close to a computer right now, but I'll take a look as soon as I can. Thanks, mate!
