### ISSUE TITLE
Goal /admin: We can login to the admin panel

### ISSUE THREAD

**Issue by webcrumbs-community** [webcrumbs-community/webcrumbs#145]

**Comment by trdxDeepu** [comment]
is login page is already there or its need to be created

**Comment by heyjmac** [comment]
We're inviting the people that signed up through the landing 
(webcrumbs.org) on a rolling basis. Right now it is a demo through call, 
cause we need the feedback to improve. Later we'll open it async!

On 2024-04-24 13:04, Deependra Singh wrote:

> is login page is already there or its need to be created
> 
> --
> Reply to this email directly, view it on GitHub [1], or unsubscribe 
> [2].
> You are receiving this because you are subscribed to this 
> thread.Message ID: 
> ***@***.***>



Links:
------
[1] 
https://github.com/webcrumbs-community/webcrumbs/issues/145#issuecomment-2075302307
[2]

**Comment by trdxDeepu** [comment]
i am asking like how can i openly contribute to the  project

**Comment by webcrumbs-community** [comment]
Hey @trdxDeepu! Great seeing you here again. So we're now giving it a pause on contributions because of the major overhaul we're working on. It's a little step back so we can relaunch with a working code and move forward from there! I don't know if you subscribed yet at webcrumbs.org, but you can be one of the first to try it out before we launch.
