### ISSUE TITLE
Localization Support

### ISSUE THREAD

**Issue by webcrumbs-community** [webcrumbs-community/webcrumbs#15]
Add support for multiple languages in the UI.

**Comment by 29deepanshutyagi** [comment]
i can work on this issue ,kindly assign me this issue under Hacktoberfest 2023 ,  @webcrumbs-community

**Comment by dshaw0004** [comment]
> i can work on this issue ,kindly assign me this issue under Hacktoberfest 2023 , @webcrumbs-community and @dshaw0004

what is Hacktoberfest ?

**Comment by webcrumbs-community** [comment]
> what is Hacktoberfest ? 

It's a super nice recognition of people that contribute to open source projects in October. Send 4 accepted PRs and that's it.

More [here](https://hacktoberfest.com).

**Comment by webcrumbs-community** [comment]
> i can work on this issue ,kindly assign me this issue under Hacktoberfest 2023 ,  @webcrumbs-community    and @dshaw0004 

@29deepanshutyagi Sorry, this shouldn't be opened yet, as we're still finalising the first code commits. Can you choose another one?
