### ISSUE TITLE
Task /core: Create a new experiment to set up state management for host and enable state updates via plugin callbacks

### ISSUE THREAD

**Issue by webcrumbs-community** [webcrumbs-community/webcrumbs#158]
#### Objective
Create a system where the host manages global state and plugins can update it via callbacks.

#### Description
We need a state management system in the host that allows plugin callbacks to modify the state. This task involves building that system, ensuring state updates.

#### Task
Create a new experiment `experiment-x` to establish state management in the host application and create a mechanism for plugins to update this state via callbacks.

#### Requirements
- Build a global state management for the host.
- Develop a callback system for plugins to update state.

#### Steps to Proceed
1. Design the global state architecture for the host application.
2. Set up the callback functions that plugins will use to modify the host state.
3. Test the integration thoroughly to ensure that state updates are handled correctly.
4. Document the process and establish guidelines for plugin developers.

#### Additional Context
This experiment is crucial for enhancing the interactivity and functionality of our platform, paving the way for more dynamic and customizable user experiences.

#### Acceptance Criteria
- [ ] Host has a functional global state management system.
- [ ] Plugins can update the host state using callbacks.

Take on this core functionality enhancement to improve our platform's interactivity!

**Comment by aditya4196** [comment]
@webcrumbs-community I would like to take on this functionality. Can you please assign it to me?
I would clarify my questions about this issue during our friday meeting.

**Comment by webcrumbs-community** [comment]
Yes, great. Let's restart the meetings next Friday!
