### ISSUE TITLE
Improve README.md readability in GitHub dark theme by fixing contrast issue

### ISSUE THREAD

**Issue by THammami01** [webcrumbs-community/webcrumbs#183]
Hello,

Considering that a majority of developers opt for the dark theme, it would be nice to adapt the repository's `README.md` file accordingly.

At the moment, it appears as follows:

![image 1](https://github.com/webcrumbs-community/webcrumbs/assets/50141415/23b7415c-6433-4249-8073-0a9bed83bfd0)

<br />

Here's an example of a proposed improvement to address the contrast issue and improve text readability:

![image 2](https://github.com/webcrumbs-community/webcrumbs/assets/50141415/192fb2f1-5e49-4570-b4fe-4dbd49255224)

<br />

Tips:

<img src="https://user-images.githubusercontent.com/3369400/139447912-e0f43f33-6d9f-45f8-be46-2df5bbc91289.png#gh-dark-mode-only" width="50" align="right" /> 
<img src="https://user-images.githubusercontent.com/3369400/139448065-39a229ba-4b06-434b-bc67-616e2ed80c8f.png#gh-light-mode-only" width="50" align="right" />

- For control over image visibility, append `#gh-dark-mode-only` or `#gh-light-mode-only` to the end of the image URL to define whether it's only shown in a light or dark GitHub theme. For instance, the following GitHub logo will differ based on the selected theme:

- Consider employing relative paths instead of absolute ones in image URLs. This not only ensures functionality even if the repository owner or name changes but also simplifies the contribution process, where modifications made in the local or forked repository will be reflected rather than those of the base repository. For instance, `./src/assets/logo.svg` instead of `https://.../src/assets/logo.svg`.

**Comment by webcrumbs-community** [comment]
Really helpful. Thanks, @THammami01. We're on it.
