### ISSUE TITLE
User Authentication

### ISSUE THREAD

**Issue by webcrumbs-community** [webcrumbs-community/webcrumbs#2]
Implement secure user authentication methods, possibly using OAuth or JWT.

**Comment by trdxlucifer** [comment]
backend can be done using supabase ?

**Comment by webcrumbs-community** [comment]
Supabase auth is great. Because we're working with Nextjs, **Next Auth** seem a pretty straightforward option, though. Would you agree?

For DB, we still have to discuss. I'll open a new discussion if it's not open already:

**Comment by webcrumbs-community** [comment]
Anyone wanting to take this one?

**Comment by shreykoradia** [comment]
is this still open I want to take a shot at it ; I am new to backend in particular to next but i know basics of express and node ??

**Comment by webcrumbs-community** [comment]
This issue is repeated. Keeping #40
