### ISSUE TITLE
Excessive permission request for waitlist

### ISSUE THREAD

**Issue by Mardoxx** [webcrumbs-community/webcrumbs#248]
Why do you need these permissions when signing up to [waitlist](https://www.webcrumbs.org/open-source)

```
- Verify your GitHub identity (Mardoxx)
- Know which resources you can access
- Act on your behalf

Email addresses (read)
    View your email addresses
```

Additionally: Why do you need tracking pixels in your github issues? (default template injects the below)

```![Analytics](https://www.google-analytics.com/collect?v=1&t=pageview&tid=G-XXXX&cid=XXX&dl=https%3A%2F%2Fgithub.com%2Fwebcrumbs-community%2Fwebcrumbs%2Fissues&dt=Issues)```

**Comment by heyjmac** [comment]
Hi Mardoxx! This flow is the default GitHub login, so unfortunately we cannot change it. 
The only permissions we ask is to read email. None else.

The analytics is misplaced (and don't work!). Thanks for noticing.

<img width="739" alt="image" src="https://github.com/user-attachments/assets/61863975-2e5d-46e9-8228-59217622d08a">

**Comment by Mardoxx** [comment]
![image](https://github.com/user-attachments/assets/fde2cdb3-c6da-48bd-8382-7ac0128cfa71)


Yeah.. no.

**Comment by Mardoxx** [comment]
You're doing something very wrong here.

**Comment by heyjmac** [comment]
That's not the intention. Help us understand, please. 
Here's what the permissions are in our GitHub app configuration. 
As you can see, the only permissions are the read for the email.

[GitHub Apps - webcrumbs-landing-page.pdf](https://github.com/user-attachments/files/17336635/GitHub.Apps.-.webcrumbs-landing-page.pdf)

**Comment by heyjmac** [comment]
The different logins you're seeing is because they use oAuth GitHub and we're using GitHub Apps. You can find more about it here: https://docs.github.com/en/apps/oauth-apps/building-oauth-apps/differences-between-github-apps-and-oauth-apps

> In general, GitHub Apps are preferred to OAuth apps because they use fine-grained permissions, give more control over which repositories the app can access, and use short-lived tokens.
