### ISSUE TITLE
🎃 Hacktoberfest Special

### ISSUE THREAD

**Issue by heyjmac** [webcrumbs-community/webcrumbs#266]
### Welcome to Webcrumbs Hacktoberfest! 🎉

This October, we’re celebrating open-source contributions by accepting community templates for our platform. 🥳 Participate by submitting your best templates—use your creativity, coding skills, and community spirit!

The top 3 contributors chosen by our [Discord community](https://discord.com/invite/ZCj5hFv8xV) will gain:

1. A special Hacktoberfest badge for your GitHub, LinkedIn, or CV
2. A shout-out on our website and newsletter
3. A special ring around your avatar in Frontend AI

Your templates must be open source under the MIT license (so everyone can use and iterate on them). Once we approve your work, your template will be live on our platform with your username proudly displayed!

Eager to start?
1. Head to [Frontend AI](https://tools.webcrumbs.org/frontend-ai?open=hacktoberfest)
2. Build something cool
3. Click the Hacktoberfest button > Submit when you're ready
4. And wait for approval and further instructions by email!

Create your component with Frontend AI and hit submit when you're ready 🚀

**Comment by Akash-cloud001** [comment]
@heyjmac assign this task to me, as my template got selected but am getting issues while cloning the repo.
Issue: after cloning the repo is blank and everything inside of it is deleted. Secondly, there a directory name **aux** which is an invalid directory name for windows user.
Please help me this issue so that i can create my pr.
Thank you

**Comment by heyjmac** [comment]
Hi @Akash-cloud001! I'll let this open so everyone can send theirs, but let us try to solve this issue that's appearing to you. Perhaps try this way and let me know if it does not work:

**The easiest way to contribute to Hacktoberfest this year (through GitHub GUI):**
**1. Fork the Webcrumbs repo (if you haven't yet)**

<img width="511" alt="image" src="https://github.com/user-attachments/assets/ef6feb28-26ea-41f8-bf7b-d0d30cfe7abb">

**2. Go to your fork. If needed, sync it.**

<img width="913" alt="image" src="https://github.com/user-attachments/assets/436c7470-eab5-4d22-aa95-48cce85276ca">

**3. Go to the contributions folder and click Add file > Upload file**

<img width="1384" alt="image" src="https://github.com/user-attachments/assets/027d270f-61bb-462c-853b-682f3f49a484">

**4. Go back to the home of your fork and click Contribute > Open pull request**

<img width="912" alt="image" src="https://github.com/user-attachments/assets/45da8c60-5fe5-4e0f-8142-f5f676a07fe4">

**5. Fill the Pull Request template and you're ready to go!**

**Comment by Akash-cloud001** [comment]
Thanks a lot, @heyjmac, this method worked for me. Please Check my pr.
