### ISSUE TITLE
Plugin API Design

### ISSUE THREAD

**Issue by webcrumbs-community** [webcrumbs-community/webcrumbs#3]
Define the specifications for the Plugin API. This will include routes, request, and response formats.

**Comment by vbrazo** [comment]
I can work on this one @webcrumbs-community

**Comment by rovoskarl** [comment]
The architecture of the plug-in can be implemented by referring to https://github.com/webpack/tapable. I am more interested in it. @webcrumbs-community

**Comment by vbrazo** [comment]
Do you want to take this one over? @rovoskarl

**Comment by rovoskarl** [comment]
Yes, if you want to do it, I can help you and make it better together.

**Comment by rovoskarl** [comment]
Yes, if you want to do it, I can help you and make it better together. @vbrazo

**Comment by webcrumbs-community** [comment]
That's great, @vbrazo and @rovoskarl. Webpack is the way to go! The architecture page at the wiki may help with an overview of the connections between the projects' parts. Let me know if you need anything. Cheers!

**Comment by vbrazo** [comment]
Sounds good. I can work on it, but I'd suggest we do a pair programming session to review the code or build together @rovoskarl. Would you be up for a 30 minute live session in the near future?

**Comment by vbrazo** [comment]
Sounds good. We can work on it together, but I'd suggest we do a pair programming session @rovoskarl. Would you be up for a 30 minute live session in the near future?

**Comment by webcrumbs-community** [comment]
Guys, @vbrazo @rovoskarl, have you seen or know if it's possible to have a Nextjs installation as a Webpack Federation Module? I'm asking cause it may affect other issues. Don't worry if you've not seen or don't know the answer, as this is something we should dig deeper at some point. Thanks, mates.

**Comment by rovoskarl** [comment]
Yes please see here https://github.com/module-federation/module-federation-examples/tree/master/nextjs-react @webcrumbs-community

**Comment by rovoskarl** [comment]
There are a lot of things going on these two days. It would be better if we could do it remotely. @vbrazo

**Comment by webcrumbs-community** [comment]
@rovoskarl Thank you so much. This is a relief.

**Comment by vbrazo** [comment]
@rovoskarl no problem. Let's take to offline, I'll think about this issue and touch base again.

**Comment by webcrumbs-community** [comment]
@vbrazo @rovoskarl Passing by to share that we've just opened the [Core Discussion](https://github.com/webcrumbs-community/webcrumbs/discussions/91). This will be the most important part for our project, for sure. Cheers!

**Comment by vbrazo** [comment]
@rovoskarl I'm going to be working on this issue https://github.com/webcrumbs-community/webcrumbs/issues/78 over the coming days, and I'd like to know if you want to take over this issue? If not, I'd like to assign this issue to another team member, @webcrumbs-community. Thanks!

**Comment by webcrumbs-community** [comment]
Hi, @vbrazo. Thanks, mate. It's good to focus.
I'll be taking the lead on this one, with inputs from all the community.
I think these experiments will help us structure the Plugin "API": `/core/experiment-1`
Cheers!

**Comment by webcrumbs-community** [comment]
I am reorganizing the issues in the form of a project, so this will come back later in time. I'm closing it for now.
