### ISSUE TITLE
Frontend of WebCrumbs.org

### ISSUE THREAD

**Issue by webcrumbs-community** [webcrumbs-community/webcrumbs#39]
Start the frontend of WebCrumbs.org using React and Nextjs. Begin "small and quick" and let the community grow it from there.

**Comment by Ashok-Kumar-dharanikota** [comment]
Hi @webcrumbs-community 

I would like to work on this issue. But can I know How the UI you want to look like? Is there a design template?

**Comment by webcrumbs-community** [comment]
Hey @Ashok-Kumar-dharanikota! Welcome the club. Give me a weak and I'll define this better. In the meantime, if you want to start a new nextjs and PR to /landing, that would be great. Cheers

**Comment by Ashok-Kumar-dharanikota** [comment]
Sure Take your time 😊. I will also go through some design inspirations or will share it in discussions. That would be helpful to generate more ideas.

**Comment by webcrumbs-community** [comment]
Perfect. We'll keep in touch

**Comment by webcrumbs-community** [comment]
Hi, @Ashok-Kumar-dharanikota. I really like how simple the content of this project is ([nativescript.org](https://nativescript.org/)). Perhaps we could think of something even more simple to begin with. I'll upload some images to the **/src/img** folder. I added a quick roadmap to the [wiki](https://github.com/webcrumbs-community/webcrumbs/wiki/Roadmap). Cheers, mate!

**Comment by Ashok-Kumar-dharanikota** [comment]
More than the project, your excitement and encouragement 😀 truly inspiring me. 

As it is, no code platform to create react Web application. It good to minimise code related snippets in our page. I think it is need to be like drag and droping of react components and also State management dashboard for specific component. 

More like in a visual way. So people understand more easily about this project. 

 (We are able to let the user do no-code operations through our dashboard)

**Comment by webcrumbs-community** [comment]
Glad to hear, man. But what's truly inspiring is how quick this community got together! I'm amazed.
Drag and drop is a must. Totally agree. 
After we'll have some basic code up there, I'll make sure to add more specific and advanced issues.

**Comment by Ashok-Kumar-dharanikota** [comment]
@webcrumbs-community , Yes i too totally agree. But I am not telling you to implement this feature early. I know it would take some time. 

I am referring to creating a svg type of animation of drag and drop of components into the website. 

Imagine it as , when the user opened the website. 

First thing He will see like

"A no-code solution to your next react project" or "Create React Application with our no-code Tool".

As hee continue to scroll. He will see some drag-&-drop animation of components (one inside another) (we can display a relevant small code snippet, where a component contains another component)  

After scrolling again,

He will see a state management board, where one text is already selected. It is specified as an integer type and in functions he can create multiple functions to do CRUD operations and more. (The dashboard not going to be that much complex, we have to apply some abstraction to it). 

Or 

We can create 10-30 sec of hands on tutorial to user to create State management of counter App by few
Simple steps. It will be great start for him to use this (It is also require some careful consideration and time). 

And promising that you can experience complete react features while using this no-code Tool. 


There are 3 Ps here
Propose
provide
promise 

Here we proposing who We are (Webcrumbs) and about our idea. 
And what we providing for the User.
And what we promising in future.

**Comment by webcrumbs-community** [comment]
Oh, I get it. It's a really good idea. I'll add it as a separate issue. Thanks for the help!

**Comment by webcrumbs-community** [comment]
Saving for later... I just love the friendly and funny tone of this copy: https://dndkit.com/

**Comment by Ashok-Kumar-dharanikota** [comment]
@webcrumbs-community me too. 🤩
The UI is close to what I have in my mind. The drag-and-drop action is really great in this. It is so helpful in our project.

**Comment by justicasimples** [comment]
Hi @Ashok-Kumar-dharanikota! I'd love to help on this. If you want to share what you have even if partial I can help from there. Let me know!

**Comment by Ashok-Kumar-dharanikota** [comment]
Hi @justicasimples , 🤗

Thank You for asking. I just explored a few UI designs that most no-code platforms follow recently. I didn't started yet.  Suppose you want to work on this issue. Please ask @webcrumbs-community once. Due to a few things, it may take a little longer for me. I will try to add up later.  

Meanwhile, your contribution will be helpful for the project. So go on. 👍

**Comment by webcrumbs-community** [comment]
@Ashok-Kumar-dharanikota, that's great! @justicasimples, if you'd like, please go for it. 🚀 Later @Ashok-Kumar-dharanikota and I can comment and we can move on with the next steps together. If you have any questions or want to discuss, we're here. Also, I'm opening a [Figma](https://www.figma.com/file/lwlAfp0wBpRnDKyxu2DRKj/webcrumbs?type=design&node-id=0%3A1&mode=design&t=NYdem9lvStsrftj2-1) so we can exchange ideas. Cheers!

**Comment by justicasimples** [comment]
Hey! An update. To speed up, I've been working with webflow, which is good for temporary websites. Later we can migrate to WebCrumbs, which I think will be the best for long-term websites! It's still on the making [here](https://anysite-2dd7be.webflow.io/).

**Comment by webcrumbs-community** [comment]
It's coming out great! Keep it up, @justicasimples. Agree that later we'll have to change it to WebCrumbs. It can even be a nice exercise - perhaps a plugin to quickly import a website from webflow? This would be fantastic.

**Comment by webcrumbs-community** [comment]
@Ashok-Kumar-dharanikota You're right. We'll have to figure that out to be attractive.

**Comment by justicasimples** [comment]
I opened a discussion at #99 !
