### ISSUE TITLE
Implement Next Auth

### ISSUE THREAD

**Issue by webcrumbs-community** [webcrumbs-community/webcrumbs#40]
## Tasks:

1. Set up the NextAuth.js library in our project at /admin.
2. Configure at least one authentication provider (e.g., Google, GitHub, or a custom provider).
3. Implement session management to protect at least one route/page.

## Acceptance Criteria:

- Users should be able to log in using the chosen authentication provider.
- After logging in, users should be able to access protected routes/pages (e.g. admin panel).
- Users should be able to log out.
- Non-authenticated users should be redirected or alerted when trying to access protected content.

**Comment by shreykoradia** [comment]
Can You please provide some description on this issue if possible ?

**Comment by webcrumbs-community** [comment]
Welcome, @shreykoradia! It's done, mate. We know the project is in really early stage, so we're accepting tiny little steps forward as PR.

**Comment by shreykoradia** [comment]
> Welcome, @shreykoradia! It's done, mate. We know the project is in really early stage, so we're accepting tiny little steps forward as PR.

Would You like to add some issues which are open or you recommend that can be contributed ??

**Comment by webcrumbs-community** [comment]
> Would You like to add some issues which are open or you recommend that can be contributed ??

Yes, we will. It's on our to-do list. Keep posted!

**Comment by webcrumbs-community** [comment]
Hello, there. Now that there is some initial code at /admin, this issue is ready to be worked on.
It still has no one assigned.

Cheers.

@shreykoradia @maida12 @dshaw0004

**Comment by shreykoradia** [comment]
Can I work on it ??

**Comment by dshaw0004** [comment]
Yes you can
@webcrumbs-community assign this task to this person

**Comment by shreykoradia** [comment]
Which Database are we using cause last time i saw [issue](https://github.com/webcrumbs-community/webcrumbs/issues/2) it was still about to discuss so if it please make sure you or I any one of us could open an issue

**Comment by shreykoradia** [comment]
I am assuming something like this as a flow  which is pretty clear indeed 
![image](https://github.com/webcrumbs-community/webcrumbs/assets/67724256/fe2833a5-aaab-4054-8f1a-7994f0f0a85d)

**Comment by webcrumbs-community** [comment]
Hey, @shreykoradia. Yes, that's right. What do you think of a local MongoDB to start?

**Comment by webcrumbs-community** [comment]
@shreykoradia  I included a diagram [here](https://github.com/webcrumbs-community/webcrumbs/wiki/Roadmap) to explain how the work we've been doing will come together

**Comment by shreykoradia** [comment]
> * ogging in, users should be able to access protected routes/pages (e.g. admin panel).

Sure I have gone through it , I am already working on it !

**Comment by Codeauthor1** [comment]
Hello there, I'm happy that @shreykoradia is picking up this task. And like to work with him on this task

**Comment by shreykoradia** [comment]
> Hello there, I'm happy that @shreykoradia is picking up this task. And like to work with him on this task

I would be happy if @webcrumbs-community  allows I don't mind already have made an signup API so  we may discuss what you can work on

**Comment by webcrumbs-community** [comment]
@shreykoradia  @shreykoradia  Couldn't be happier. Go for it!

**Comment by shreykoradia** [comment]
I have already made a custom Provider  Signup API  and now  integrating next auth may be  I may do it tomorrow night , If you want to contribute you may start with GitHub provider may be it will be beneficial

**Comment by Codeauthor1** [comment]
Copy that. I'm currently working on setting up the project on my machine, but I'm encountering an issue where the "next.js dev server" isn't initiating as expected. Strangely, it's not providing any error logs on the console either.

**Comment by shreykoradia** [comment]
> Copy that. I'm currently working on setting up the project on my machine, but I'm encountering an issue where the "next.js dev server" isn't initiating as expected. Strangely, it's not providing any error logs on the console either.

Oh  Okay I guess you need to  go at clone folder and cd admin and run npm run dev

**Comment by Codeauthor1** [comment]
I have done that. it starts the process and then exits without any errors

**Comment by shreykoradia** [comment]
> I have done that. it starts the process and then exits without any errors

I mean I have already done that stuff and it worked ,  just look properly once or might ask @webcrumbs-community

**Comment by Codeauthor1** [comment]
It's likely that the issue originates from my machine, I initialized a new Next.js application, but the outcome remains constant

**Comment by shreykoradia** [comment]
Hello I have already Implemented the signup and login flow but I am bit  confused on the part of the authentication gaurd to protect the routes it may be I have never worked on that part especially in next js so i need some guidance if any one up @webcrumbs-community  @dshaw0004  @maida12

**Comment by webcrumbs-community** [comment]
Hi, @shreykoradia. Didn't test, but I think of something like this:

```
import { useSession } from 'next-auth/react';
import { useRouter } from 'next/router';
import { useEffect } from 'react';

export default function ProtectedPage() {
  const { data: session, status } = useSession();
  const isUserLoading = status === 'loading';
  const router = useRouter();

  useEffect(() => {
    if (isUserLoading) return; // Do nothing while loading
    if (!session) router.push('/login'); // Redirect to `/login` if no session exists
  }, [session, isUserLoading, router]);

  if (isUserLoading) {
    return <p>Loading...</p>;
  }

  return (
    <div>
      <h1>Protected Page</h1>
      <p>This is a protected page.</p>
    </div>
  );
}

```

**Comment by shreykoradia** [comment]
Hey man I know this part but I haven't create the routes that way I don't have that knowledge havent created any project from scratch ! @webcrumbs-community

**Comment by webcrumbs-community** [comment]
Oh, sure. We're working at /admin project. The routes are implicitly managed by nextjs, so you should add this code to the admin/pages/admin.tsx

**Comment by shreykoradia** [comment]
> Oh, sure. We're working at /admin project. The routes are implicitly managed by nextjs, so you should add this code to the admin/pages/admin.tsx

I guess this isn't a good way cause we should create a HOC for the authentication I got a way I will try it out if it is possible and then push might be gonna complete this weekend

**Comment by shreykoradia** [comment]
Okay I have finished with the stuff more over i have created if you guys want to use it please go ahead I am creating a pull req

**Comment by webcrumbs-community** [comment]
Thanks for it, men!

**Comment by shreykoradia** [comment]
> Thanks for it, men! Good work there.

It means a lot ! , If there are any more issues please let me know i am open to contribute

**Comment by webcrumbs-community** [comment]
I'll create a new issue on this same topic, if you wanna check. Can't think of anyone better. Cheers!
