### ISSUE TITLE
Initial setup at /demo using react

### ISSUE THREAD

**Issue by webcrumbs-community** [webcrumbs-community/webcrumbs#47]
Have a first simple website at /demo using react

**Comment by trdxlucifer** [comment]
LIKE WHAT KIND OF WEBSITES

**Comment by webcrumbs-community** [comment]
I'd start simple with this content:

Hello world!
Welcome to WebCrumbs. This is your first website. Soon you'll be able to edit or delete it, and start writing!
Friday, October 6, 2023

See [/admin/pages/index.tsx](https://github.com/webcrumbs-community/webcrumbs/blob/main/admin/pages/index.tsx) for instance.

Cheers!

**Comment by trdxlucifer** [comment]
ok i can do it

**Comment by webcrumbs-community** [comment]
That's great. I've assigned it to you @trdxlucifer

**Comment by webcrumbs-community** [comment]
Beautiful.
