### ISSUE TITLE
Initial setup at /registry using nextjs

### ISSUE THREAD

**Issue by webcrumbs-community** [webcrumbs-community/webcrumbs#48]
Have an initial non-functional form to upload plugins at /registry.
Suggested content for the first page:

---

### Welcome, Developer
We're pleased you're interested in enriching the WebCrumbs community with your plugin. To ensure a smooth process, please familiarize yourself with our [Guidelines](#) and [Frequently Asked Questions](#).

---

### Plugin Submission Steps

**Upload File**:  _[dropzone]_
Maximum File Size: 10 MB

_[bellow are checkboxes]_
- [ ] Reviewed the [Frequently Asked Questions](#)
- [ ] Complies with [Developer Guidelines](#)
- [ ] Authorized for public sharing
- [ ] Compatible license for open sharing

Upon submission, our team will carefully review your plugin for quality assurance and guideline adherence.

---

### What is the Review Duration?
We prioritize efficient review procedures. While the time frame can vary, our goal is to approve plugins in 1 day.

### How is the Plugin URL Generated?
Your plugin URL is formulated based on your Plugin Name. For example, if your plugin is called "InnovateMe," your URL will be `https://registry.webcrumbs.org/innovateme`.

### Made an Error in the Plugin Name?
If you notice an error in your plugin name, contact us at plugins@webcrumbs.org. We can adjust it before your plugin becomes publicly available.

### Restrictions on Plugin Names?
Certain names are restricted to avoid any potential trademark conflicts. This is a measure for your protection.

---

### Support Our Mission
If you find value in what WebCrumbs is achieving, consider starring our [GitHub repository](https://github.com/webcrumbs-community/webcrumbs).

**Comment by webcrumbs-community** [comment]
@trdxlucifer would you like to take this one too? very similar to #47. I loved the style you used there. Only if you'd like. Don't feel obliged. Cheers!

**Comment by trdxlucifer** [comment]
I would love to do that yeah ofcourse

**Comment by webcrumbs-community** [comment]
Perfect, mate. Assigned. Cheers.

**Comment by trdxlucifer** [comment]
Do I need to fork again the repository or i have to use the one I was doing ??

**Comment by webcrumbs-community** [comment]
There were some PRs in the middle. Please pull the changes first. Tks!

**Comment by trdxlucifer** [comment]
there is no registry folder do i need to create one ?

**Comment by webcrumbs-community** [comment]
Yes, please. Tks, mate

**Comment by trdxlucifer** [comment]
i was trying to npx install its only showing error

**Comment by trdxlucifer** [comment]
i dont know typescript  but wanna learn and do i need to use only pagerouting or else i use approuting coz i am new into nextjs

**Comment by webcrumbs-community** [comment]
Let me help. One second

**Comment by webcrumbs-community** [comment]
Pull the repo and you'll now find the /registry folder, with nextjs and material ui installed (more [here](https://mui.com/material-ui/getting-started/)). Would you add a non-functional form that will allow devs to submit plugins in the future?

**Comment by trdxlucifer** [comment]
Can u explain me what are plugins

**Comment by trdxlucifer** [comment]
I m new into this so I don't know anything about

**Comment by webcrumbs-community** [comment]
Sure! Don't worry. In the "WordPress World" plugins are add-ons to the website that can extend them to any functionality you can imagine. For instance, there are plugins that turns the "blog" into a e-commerce page. Others that do simpler things such as adding a poll. Here's [a list of WordPress plugins](https://wordpress.org/plugins/) so you can have an idea of all things they can do.

I'll add more description to the issue, and you'll let me know if you have any questions.

**Comment by webcrumbs-community** [comment]
@trdxlucifer I included a diagram [here](https://github.com/webcrumbs-community/webcrumbs/wiki/Roadmap) to explain how the work we've been doing will come together
