### ISSUE TITLE
Create a Mockup image of WebCrumbs for the /landing

### ISSUE THREAD

**Issue by webcrumbs-community** [webcrumbs-community/webcrumbs#49]
As per @Ashok-Kumar-dharanikota suggestion at #39:

Imagine it as , when the user opened the website.

First thing He will see like

"A no-code solution to your next react project" or "Create React Application with our no-code Tool".

As hee continue to scroll. He will see some drag-&-drop animation of components (one inside another) (we can display a relevant small code snippet, where a component contains another component)

**Comment by AJBrownson** [comment]
Hi @webcrumbs-community 
I would love to work on this issue
Could you please clarify with examples how you need the image to be like?

**Comment by webcrumbs-community** [comment]
This is great, @AJBrownson! I think you can look up for "drag and drop website builder" in Google images for inspiration. Something more conceptual, low fidelity would work best. I found this one for instance: ![image](https://github.com/webcrumbs-community/webcrumbs/assets/116091091/36ab70e1-f96a-40ec-b5a6-845b1d432f7a)

Cheers!

**Comment by Ashok-Kumar-dharanikota** [comment]
Hi @AJBrownson , 
Welcome to the community, 🤝

Happy to have you here 😊. Thank you for taking the initiative to work on this issue. You can check out this site for inspiration. 
https://dndkit.com/

**Comment by ayobamiseun** [comment]
Can i work on the landing to address this issue and also add some additional design to make it more user friendly.

**Comment by webcrumbs-community** [comment]
Hi, @ayobamiseun. @Ashok-Kumar-dharanikota is working on improving the front under #(). I'll let him tell you how you can help! Cheers

**Comment by ayobamiseun** [comment]
> Hi, @ayobamiseun. @Ashok-Kumar-dharanikota is working on improving the front under #39. I'll let him tell you how you can help! Cheers

I just saw it now. If you need to work on the design in another section, please raise an issue, and I will work on it.

**Comment by AJBrownson** [comment]
@webcrumbs-community I have gone through the   website you dropped before 
Is it something like a GIF 

> Hi @AJBrownson , Welcome to the community, 🤝
> 
> Happy to have you here 😊. Thank you for taking the initiative to work on this issue. You can check out this site for inspiration. https://dndkit.com/

I just looked at the site and it's really nice
So I'm working on an image like that right?
An animation showing how webcrumbs work?

**Comment by webcrumbs-community** [comment]
Yes! Please feel free to make a suggestion.

**Comment by webcrumbs-community** [comment]
Guys, @AJBrownson @Ashok-Kumar-dharanikota I included a diagram [here](https://github.com/webcrumbs-community/webcrumbs/wiki/Roadmap) to explain how the work we've been doing will come together. Cheers!

**Comment by webcrumbs-community** [comment]
Hi @AJBrownson, how you doing? Let us know if you need anything on this front. Cheers, mate!

**Comment by webcrumbs-community** [comment]
What do you think if we go with the one on the README.md for the time being? I don't know if you already started something and would like to share. Otherwise I'd close the issue for now. Let me know!

**Comment by AJBrownson** [comment]
@webcrumbs-community sorry for my delay in replying back 
I just checked the README.md and the design looks good
We can close this issue for now

**Comment by webcrumbs-community** [comment]
Thanks! I'm closing for now. Cheers
