### ISSUE TITLE
Admin Dashboard UI

### ISSUE THREAD

**Issue by webcrumbs-community** [webcrumbs-community/webcrumbs#5]
Design and implement the user interface for the admin dashboard where users can manage plugins.

**Comment by webcrumbs-community** [comment]
@dshaw0004, is it right to assign this to you?

**Comment by dshaw0004** [comment]
It's okay but I am busy at my job lately. So I will not be able to give my 100%.

**Comment by webcrumbs-community** [comment]
Don't worry, @dshaw0004. Perhaps the title just be renamed. It should read "small incremental steps towards ...". Little steps compound!

**Comment by webcrumbs-community** [comment]
@dshaw0004 See if there's something you'd like to add to /admin - otherwise I think we can close this for now and create more specific issues later. Do you agree? Cheers!

**Comment by dshaw0004** [comment]
@webcrumbs-community nothing for now. I will create a new issue if needed.
