### ISSUE TITLE
Generate a bundle of the admin panel at **/src** with webpack and add to the website at **/demo** with <script>

### ISSUE THREAD

**Issue by webcrumbs-community** [webcrumbs-community/webcrumbs#51]
### Objective 🎯

- Create a Webpack configuration to bundle the admin panel code from the `/src` directory.
- After bundling, add the generated script to the `/demo` directory of our website using a `<script>` tag.

### Steps to accomplish this ✅

1. Navigate to the `/src` directory where the admin panel code resides.
2. Create or modify the existing Webpack configuration file to include the admin panel.
3. Run Webpack to generate the bundled script.
4. Move the bundled script to the `/demo` directory.
5. Integrate this script into the demo site using a `<script>` tag.

### Additional context 📝

Make sure you thoroughly test the bundled admin panel in the demo site to ensure it's working as expected. Feel free to reach out if you encounter any issues or have questions.

**Comment by Yogeshp0012** [comment]
Can I work on this?

**Comment by webcrumbs-community** [comment]
Sure! Go for it 💪

**Comment by Yogeshp0012** [comment]
Hi @webcrumbs-community , i cannot see any `/src` directory inside the admin folder

**Comment by webcrumbs-community** [comment]
Oh, it doesn't exist yet. Please feel free to create it. Cheers!

**Comment by webcrumbs-community** [comment]
@Yogeshp0012 I understand this is one of the most difficult tasks we have at the moment. I included a diagram [here](https://github.com/webcrumbs-community/webcrumbs/wiki/Roadmap) to explain how the work we've been doing will come together. Let me know if you have any questions. Cheers!

**Comment by Yogeshp0012** [comment]
@webcrumbs-community, currently piled up with a lot of work. You can reassign this to someone who wants to work on it.

**Comment by ayobamiseun** [comment]
@webcrumbs-community & @Yogeshp0012  if this issue is still open can i give it a shot ✊

**Comment by webcrumbs-community** [comment]
This one is our challenge. 👀Everyone is welcome to give a shot! 💪 I'll let this one as a first come first served base.

**Comment by ayobamiseun** [comment]
@webcrumbs-community  am i suppose to add an index to the demo directory before i can call the script tag ?

**Comment by webcrumbs-community** [comment]
@ayobamiseun I guess it can be at `demo/pages/_document.tsx`. What do you think?

**Comment by ayobamiseun** [comment]
@webcrumbs-community  sent a PR regarding this.

**Comment by webcrumbs-community** [comment]
Received, @ayobamiseun! Thanks. 💪 When you tried, did it added the `localhost:3000/admin` to the `/demo` or there are more steps needed? Cheers!

**Comment by ayobamiseun** [comment]
i doubt if i can set that in the, i will appreciate if you can give me more explanation regarding this requirement.

**Comment by webcrumbs-community** [comment]
I don't have the answer now, but I'm hoping to find it on my book list. I know there are many ways of doing it (routing in micro frontends), there's probably a way that's better in our case.

![image](https://github.com/webcrumbs-community/webcrumbs/assets/116091091/72cc517e-5b2f-4e04-8850-a057d798fa61)

**Comment by ayobamiseun** [comment]
I actually saw we can use routing to achieve this, I will probably just do that. 
Set the home to localhost:3000/admin. 

I  will love to check those books out, can you  give me the names and author name.

**Comment by webcrumbs-community** [comment]
Will do! In the meanwhile, I sent you a gift of an Udemy course that may give us some ideas.

**Comment by ayobamiseun** [comment]
Wow i just got it 😄😁 i really really do appreciate it. i will check the course i am so sure it will help me in working on this.

**Comment by webcrumbs-community** [comment]
Here it is!

1. [The Art of Micro Frontends by Florian Rappl](https://www.amazon.com/The-Art-Micro-Frontends-compositional-application/dp/1800563565)
2. [Micro Frontends in Action by Michael Geers](https://www.amazon.com/Micro-Frontends-Action-Michael-Geers/dp/1617296872)
3. [Building Micro-Frontends by Luca Mezzalira](https://www.amazon.com/Building-Micro-Frontends-Scaling-Empowering-Developers/dp/1492082995)

**Comment by ayobamiseun** [comment]
The links aren’t working. I don’t know if I can get them as a mail.

**Comment by webcrumbs-community** [comment]
The second book I've mentioned has a code for routing that may give us some ideas. You can find it [here](https://github.com/naltatis/micro-frontends-in-action-code/blob/master/13_client_side_flat_routing/app-shell/index.html)

**Comment by webcrumbs-community** [comment]
> The links aren’t working. I don’t know if I can get them as a mail. 

I think I solved the broken links

**Comment by ayobamiseun** [comment]
I just got it. Appreciate 🫶

**Comment by webcrumbs-community** [comment]
@ayobamiseun Passing by to share that we've just opened the [Core Discussion](https://github.com/webcrumbs-community/webcrumbs/discussions/91). This will be the most important part for our project, for sure. Cheers!

**Comment by webcrumbs-community** [comment]
Suggestion: we can deal with this challenge as an `/core/experiment-x`, improving from the previous one. Experiment-1 is half way there, but it still needs to be bundled and added to an another package.
