### ISSUE TITLE
Task /registry: Create the UX/UI for the plugin search page on /registry

### ISSUE THREAD

**Issue by webcrumbs-community** [webcrumbs-community/webcrumbs#54]
Inspirations:
- https://wordpress.org/plugins/
- https://tairo.cssninja.io/dashboards/jobs

**Comment by webcrumbs-community** [comment]
@AJBrownson would you be up to this? Cheers!

**Comment by Dinushan-S** [comment]
hi can i work on it?

**Comment by webcrumbs-community** [comment]
Hello, @Dinushan-S! Welcome, mate. Yes, sure. Let me know if you have any questions. I hope the graph on the [Roadmap](https://github.com/webcrumbs-community/webcrumbs/wiki/Roadmap) makes it a little bit more clear where it fits in the project.

Make sure to ⭐️ star our repo and invite your friends so our community can continue growing!

**Comment by Dinushan-S** [comment]
can you guide me where can i start or how😁? ,i am new to the open source contribution

**Comment by webcrumbs-community** [comment]
Yes, sure! 

1.  Clone the repo locally with `git clone https://github.com/webcrumbs-community/webcrumbs.git`
2. Go to the directory with `cd webcrumbs`
3. Run the repo in dev mode `npm run dev`
4. Create a `plugins.txs` page at `registry/pages/`
5. Work your magic for the UI/UX using material ui components
6. Open `https://localhost:3000/` to see your changes
7. When you are happy with it, commit with `git commit -m 'Created UX/UI for the plugin search page #54'` (or similar)
8. Submit it with `git push`

Happy coding!

**Comment by webcrumbs-community** [comment]
Hi, @Dinushan-S! Hope you're good and learning a lot about open source in this special month. I'm just passing by to check if you need any help with this one. Cheers!

**Comment by Dinushan-S** [comment]
ok , thank you

**Comment by AJBrownson** [comment]
@Dinushan-S Hey!
How's it going?

**Comment by webcrumbs-community** [comment]
@Dinushan-S let us know if we can help!

**Comment by Dinushan-S** [comment]
hey sorry!! , i checking on that  bit hard to understand , can you please explain step by step ?
