### ISSUE TITLE
Write Hello Dolly plugin in javascript

### ISSUE THREAD

**Issue by webcrumbs-community** [webcrumbs-community/webcrumbs#55]
### Objective 🎯

- Develop a basic plugin in the `/plugins` directory.
- Utilize Webpack for building the plugin.
- The plugin should display the message "Hello, Dolly" when invoked.

### Why it matters ❓

Getting a simple plugin up and running will serve as a stepping stone for more complex plugins in the future. It's all about laying the groundwork.

### How to go about it ✅

1. Navigate to the `/plugins` directory.
2. Create a new plugin directory if it doesn't exist already.
3. Create a Webpack configuration for the plugin.
4. Write the code in javascript to display "Hello, Dolly."
5. Build the plugin using Webpack.
6. Test to make sure the plugin works as expected.

### Additional Info 📝

Once it's done, let's all take a moment to review and test the plugin to ensure it works flawlessly. Questions or concerns? Reach out!

**Comment by webcrumbs-community** [comment]
@ayobamiseun I included a diagram [here](https://github.com/webcrumbs-community/webcrumbs/wiki/Roadmap) to explain how the work we've been doing will come together

**Comment by ayobamiseun** [comment]
@webcrumbs-community are we using php at all for the plugins ? i saw an existing files with a wp plugin

**Comment by webcrumbs-community** [comment]
Hi! No php, just JavaScript. We will replace the plug-in that was written in php.

**Comment by webcrumbs-community** [comment]
Hi, @ayobamiseun. Hope you're having a wonderful day, my friend. I'm just passing by to check if you need any help with this one. Cheers!

**Comment by ayobamiseun** [comment]
@webcrumbs-community i already raise a PR regarding this, since last week kindly check.

**Comment by webcrumbs-community** [comment]
Oh, my bad. It was approved by another member of our team. Thank you, @ayobamiseun. I'll close the issue then. Cheers!

**Comment by ayobamiseun** [comment]
@webcrumbs-community  why am i not showing as a contributor

**Comment by webcrumbs-community** [comment]
Let us investigate

**Comment by webcrumbs-community** [comment]
@ayobamiseun It's really strange. I'm sorry for that. You're contribution has been merged, but GitHub does not include you as a contributor. The images in our Readme.md are generated automatically by a bot, based on GitHub's info. My suggestion: (1) try starring the repo and, if even then you do not appear, (2) add any change to the repo (it can be as simple as adding a space to a file). What do you say?

**Comment by ayobamiseun** [comment]
@webcrumbs-community  ok good. I just created a PR now kindly check

**Comment by webcrumbs-community** [comment]
It worked! In about 5min it must be up on the Readme.md too.
