### ISSUE TITLE
React Component Library

### ISSUE THREAD

**Issue by webcrumbs-community** [webcrumbs-community/webcrumbs#6]
Develop a library of reusable React components to be used throughout the project.

**Comment by maida12** [comment]
I can work on it

**Comment by webcrumbs-community** [comment]
Lovely, @maida12. Welcome to WebCrumbs!

**Comment by webcrumbs-community** [comment]
@maida12 I included a quick diagram [here](https://github.com/webcrumbs-community/webcrumbs/wiki/Roadmap) to explain how the work we've been doing will come together

**Comment by webcrumbs-community** [comment]
We'll continue this matter as a MaterialUI styling at `/admin`. Cheers!
