### ISSUE TITLE
ALL: Star the WebCrumbs repository

### ISSUE THREAD

**Issue by webcrumbs-community** [webcrumbs-community/webcrumbs#63]
Hurry up! ❤️

**Comment by itsayopapi** [comment]
@webcrumbs-community I have already Starred the repo. What is next for me to do?

**Comment by webcrumbs-community** [comment]
> @webcrumbs-community I have already Starred the repo. What is next for me to do?

Great, @itsayopapi! You may want to check for open issues, see our wiki, add to discussions and invite your mates. Any particular topic you like?

**Comment by itsayopapi** [comment]
Cool, I'll check it out.

you can assign anything to me

**Comment by Blossomeze** [comment]
Done✅

**Comment by Gurnav224** [comment]
Hello! 🚀 I'm in the early stages of my programming journey and am excited to connect with like-minded individuals to learn from them and grow together. 🌱 Let's embark on this coding adventure together! 😄👩‍💻👨‍💻

**Comment by webcrumbs-community** [comment]
Welcome, @Gurnav224! So good to have you here.

Check our [roadmap](https://github.com/webcrumbs-community/webcrumbs/wiki/Roadmap), our [discussions](https://github.com/webcrumbs-community/webcrumbs/discussions), and our [issues](https://github.com/webcrumbs-community/webcrumbs/issues). We add new issues almost every day.

Let us know if there's a special area you'd like to contribute.

❤️

**Comment by Gurnav224** [comment]
I am interested to contribute to frontend

**Comment by dew-dr0p** [comment]
Done✅
