### ISSUE TITLE
Make a better dashboard design

### ISSUE THREAD

**Issue by webcrumbs-community** [webcrumbs-community/webcrumbs#64]
The current design does not look the best :)
I would be happy if somebody could contribute a better design that reflects the image at readme.md.
The task can have multiple assignees.

**Comment by shubhalgupta** [comment]
please assign this task to me!

**Comment by shubhalgupta** [comment]
Also, do you have any design in mind?

**Comment by webcrumbs-community** [comment]
@shubhalgupta please see this [figma](https://www.figma.com/file/lwlAfp0wBpRnDKyxu2DRKj/webcrumbs?type=design&node-id=0%3A1&mode=design&t=NYdem9lvStsrftj2-1) and also feel free to make suggestions 💪
