### ISSUE TITLE
Task /admin: Integrate the logic of /auth to UI of /login at /admin

### ISSUE THREAD

**Issue by webcrumbs-community** [webcrumbs-community/webcrumbs#67]
#### Description
In our `/admin` dashboard, we've got a "login" page with the looks but no moves, and an "auth" page with the moves but no looks. Let's bring them together to create a unified, functional, and attractive login page. But let's not forget, this isn't just a merger—it's also a security play. The integrated `login` page should serve as the protector of the realm, or in this case, the `/admin` panel.

#### Requirements
- Fuse the logic from `/auth` into the UI of `/login`
- Maintain the UI integrity on `/login`
- Test the combined `/login` for functionality and visual fidelity
- Add a security layer to `/login` to restrict unauthorized access to `/admin`
- Bid farewell to the standalone `/auth` page upon successful integration and security implementation

#### Steps to Reproduce
1. Trek over to `/admin` on your local dev environment
2. Peek into both the `login` and `auth` pages
3. Merge the logic from `auth` into `login`
4. Confirm that `login` retains its visual charm while gaining new functional muscles
5. Implement a security measure that keeps the `/admin` panel under lock and key
6. Once all checks pass, put the `/auth` page out to pasture

#### Additional Context
We're not just pairing two lonely hearts here; we're also turning `login` into the security bouncer for our `/admin` hotspot.

#### Acceptance Criteria
- [ ] Logic from `/auth` finds a happy home in `/login`
- [ ] `Login` doesn't lose its visual sparkle after the operation
- [ ] `Login` adds a new line to its résumé: Security Guard for `/admin`
- [ ] `/auth` page is taken off the roster after everything checks out

Enough talk. It's showtime!

**Comment by DaveKobrin** [comment]
Is this going to be using an auth provider or are you self managing user account data? I have worked with a third party user auth that was very good and allows for sign in with google, facebook, github, etc... and they take care of encrypting and storing the sensitive data for you. check out [Auth0](https://auth0.com/) by Okta.

**Comment by shreykoradia** [comment]
> Is this going to be using an auth provider or are you self managing user account data? I have worked with a third party user auth that was very good and allows for sign in with google, facebook, github, etc... and they take care of encrypting and storing the sensitive data for you. check out [Auth0](https://auth0.com/) by Okta.

Actually the first issue thst is stated above consist was done by where i have already done custom provider where user sign up with email and password and can create account and login via next auth which manages the session for us that is working for admin on /auth route

**Comment by shreykoradia** [comment]
Can you give  more specifics about the  issue  it will be helpful @webcrumbs-community

**Comment by DaveKobrin** [comment]
When we have users creating accounts, webcrumbs will be legally responsible for keeping that data safe. It may be easier/safer to have an authorization provider handle that. Auth0 is one such provider. Their API is very flexible and easy to use and can allow users to log in with various social accounts or with an email/password that they will store for us. The API provides auth tokens and handles the requests to the social providers for permissions and everything. 

I'm happy to chat more about my experience with this or help to set it up if that is the way we proceed.

**Comment by webcrumbs-community** [comment]
@DaveKobrin Welcome! You're our 100 stargazer. I don't know if you know. 👊

You have valid points on the auth stack. Here's how I see it. 

We can have a native solution, as the one we're working on. At some point, we'll have to double down on security, and revise code for vulnerabilities. This will come as we grow.

But adding on that. Our philosophy is that "everything can be a plug-in". So I see alternative login solutions being offered by the community eventually (perhaps yourself even!). WebCrumbs users will know best. What do you think?

**Comment by Raghul18** [comment]
@webcrumbs-community  : [Clerk Authentication](https://clerk.com/docs/quickstarts/nextjs) provides a default setup for nextjs project and we have many auth providers as in the image below. If it's fine i can try integrating clerk into this application.
![image](https://github.com/webcrumbs-community/webcrumbs/assets/123321540/5d383e4d-8cdd-4852-828c-2e7836cc10f0)

**Comment by webcrumbs-community** [comment]
Hi, @Raghul18! Welcome! I'll start a new issue and mention you there, so we can keep things separate! One sec

**Comment by webcrumbs-community** [comment]
> Can you give more specifics about the issue it will be helpful @webcrumbs-community

Sorry for the poor description! Will improve it above. Just a sec

**Comment by webcrumbs-community** [comment]
@shreykoradia I noticed this 'native auth' continuation is not assigned yet. Would you like to take over?

**Comment by shreykoradia** [comment]
Hey it would be pleasure for me to take but I am busy this weekend as well I already looked it when  I asked you for the changes on description, but if any one up for taking it please give them otherwise reverting back from next week i guess !

**Comment by dew-dr0p** [comment]
Would love to work on this. Let me get to it right away.

**Comment by dew-dr0p** [comment]
@webcrumbs-community I'm trying to test the functionality of the auth page, I just discovered, that I don't have the environment variable that contains the URI to access the database. I'm getting an error in that regards.

**Comment by webcrumbs-community** [comment]
Hi, @dew-dr0p! Glad that you're tackling this one too. For now we're using our own installation to test it. You can create a db locally following [these instructions](https://www.mongodb.com/basics/create-database). With Compass is pretty straightforward. A local URI looks like `mongodb://localhost:27017/<database>`. Please tell me if it doesn't work.

**Comment by dew-dr0p** [comment]
> Hi, @dew-dr0p! Glad that you're tackling this one too. For now we're using our own installation to test it. You can create a db locally following [these instructions](https://www.mongodb.com/basics/create-database). With Compass is pretty straightforward. A local URI looks like `mongodb://localhost:27017/<database>`. Please tell me if it doesn't work.

I'm still having issues with the connection even after creating my database

**Comment by webcrumbs-community** [comment]
Hmm... let us see. Can you detail it a little bit?

**Comment by dew-dr0p** [comment]
Okay so I created a database, and when trying to connect it with compass, I keep on getting this error or something similar

140683213910096:error:10000438:SSL routines:OPENSSL_internal:TLSV1_ALERT_INTERNAL_ERROR:../../third_party/boringssl/src/ssl/tls_record.cc:592:SSL alert number 80

I've tried using certificates for connecting rather than password, but it still throws an error, very similar or same thing.

**Comment by webcrumbs-community** [comment]
I'm sharing a tmp URI just for you, but I'll need to whitelist your IP:

mongodb+srv://contributor:A5rOYoJZWU0Qb0fm@webcrumbsdev.fllj3wr.mongodb.net/?retryWrites=true&w=majority

Tell me when you copy it

**Comment by dew-dr0p** [comment]
@webcrumbs-community just copied it.

How do I share my IP to you?

**Comment by webcrumbs-community** [comment]
You can send it here and delete after that, or email me at community@webcrumbs.org

**Comment by dew-dr0p** [comment]
> community@webcrumbs.org

Sent

**Comment by webcrumbs-community** [comment]
Key! It's whitelisted

**Comment by dew-dr0p** [comment]
Still getting an issue @webcrumbs-community . Same issue as before
<img width="1251" alt="image" src="https://github.com/webcrumbs-community/webcrumbs/assets/44666155/23610b6e-8d07-41b6-862a-aac4074146fd">
Here's a screenshot.

I'm not sure what the problem is.

**Comment by webcrumbs-community** [comment]
Hm... 1) Try `export MONGODB_URI=[uri_here]` and 2) Check if your IP is correct (eg. [here](https://whatismyip.com.br/))

**Comment by dew-dr0p** [comment]
> Hm... 1) Try `export MONGODB_URI=[uri_here]` and running the app directly (you won't need compass or a local mongodb installation for the uri I gave you) and 2) Check if your IP is correct (eg. [here](https://whatismyip.com.br/))

Use this address: [102.90.44.35](https://www.whatismyip.com/ip/102.90.44.35/)

**Comment by webcrumbs-community** [comment]
I just whitelisted the latest IP. Let me know!

**Comment by dew-dr0p** [comment]
Great, connection to database works fine, but then I get this:

 MongoNetworkError: 001303D801000000:error:0A000438:SSL routines:ssl3_read_bytes:tlsv1 alert internal error:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1605:SSL alert number 80

    at connectionFailureError (/Users/wisdom-daniel/Documents/Projects/Web Dev/webcrumbs/admin/node_modules/mongodb/lib/cmap/connect.js:367:20)
    at TLSSocket.<anonymous> (/Users/wisdom-daniel/Documents/Projects/Web Dev/webcrumbs/admin/node_modules/mongodb/lib/cmap/connect.js:290:22)
    at Object.onceWrapper (node:events:628:26)
    at TLSSocket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  cause: [Error: 001303D801000000:error:0A000438:SSL routines:ssl3_read_bytes:tlsv1 alert internal error:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1605:SSL alert number 80
  ] {
    library: 'SSL routines',
    reason: 'tlsv1 alert internal error',
    code: 'ERR_SSL_TLSV1_ALERT_INTERNAL_ERROR'
  },
  connectionGeneration: 56,
  page: '/api/[auth]/register',
  [Symbol(errorLabels)]: Set(1) { 'ResetPool' }
}

**Comment by dew-dr0p** [comment]
It works fine now.

**Comment by dew-dr0p** [comment]
I've raised a pull request, check to confirm the issue is solved.
