### ISSUE TITLE
Continue working on the demo frontend

### ISSUE THREAD

**Issue by webcrumbs-community** [webcrumbs-community/webcrumbs#68]
Could continue working on the demo, making the home page a little bit like this: 

![image](https://github.com/webcrumbs-community/webcrumbs/assets/116091091/bd53e93e-536a-491d-a9be-fb69cfad28e9)

_Originally posted by @webcrumbs-community in https://github.com/webcrumbs-community/webcrumbs/issues/4#issuecomment-1761837135_

**Comment by aditya4196** [comment]
We are a group of 4 programmers and we would like to contribute building this frontend demo

**Comment by webcrumbs-community** [comment]
Thanks, mate. Go for it. Let me know if there are any questions. I think the Wiki here at GitHub may help get an overview of the project. Cheers!

**Comment by vlbeta** [comment]
is there a live demo anywhere to try?

**Comment by webcrumbs-community** [comment]
Hi, @vlbeta! Welcome here. We're currently working on a major overhaul of the project and aim to relaunch the repository soon. While you're here, you can sign at webcrumbs.org to be notified when we launch. See you!
