### ISSUE TITLE
Project README Update

### ISSUE THREAD

**Issue by webcrumbs-community** [webcrumbs-community/webcrumbs#8]
Keep the README.md file updated as we growth.

**Comment by 29deepanshutyagi** [comment]
i want to work on this issue ,kindly assign me @webcrumbs-community

**Comment by webcrumbs-community** [comment]
Great! Done

**Comment by webcrumbs-community** [comment]
@29deepanshutyagi  I included a quick diagram [here](https://github.com/webcrumbs-community/webcrumbs/wiki/Roadmap) to explain how the work we've been doing will come together

**Comment by marameref** [comment]
Is this issue still open pls? I wish to work on it

**Comment by webcrumbs-community** [comment]
Hi, @marameref! Welcome!This is done but is a never ending task. 😅 One thing that would be awesome would be to create an SVG file with the flag images, one that is easy to maintain and add other flags as we growth. Are you familiar with SVG code and would be up for the challenge?

**Comment by marameref** [comment]
sure, am up for the challenge.. how do i get started, where do i access the source files

**Comment by webcrumbs-community** [comment]
That's great! 🍀 Please create a COUNTRIES.svg file at the main directory. You'll find the current countries at the README.md file.

**Comment by Blossomeze** [comment]
I am interested in working on this issue, please assign me @webcrumbs-community and @dshaw0004

**Comment by webcrumbs-community** [comment]
Hey, @Blossomeze. Welcome!

Please give us a ⭐️ and tell your friends, so we can continue growing.

If you'd like, please ask @marameref if you can assist in anyway with the segregation of the flags svg to another file. Other than that, the file it's pretty up to date. 

Cheers!

**Comment by webcrumbs-community** [comment]
Guys, I realized this issue is mixed up, so I am closing this and opening a new one. I'll call you there.
