### ISSUE TITLE
API Endpoints

### ISSUE THREAD

**Issue by webcrumbs-community** [webcrumbs-community/webcrumbs#9]
Hello good people! If you're interested in helping WebCrumbs communicate seamlessly with WordPress, this task is for you. And don't worry if you're a beginner; you're more than welcome here!

### The Task
1. **Research WordPress API**: Just a quick skim to understand the basics of how WordPress sets up its API endpoints.

2. **Draft a Markdown File**: Summarize your findings and create a list of potential API endpoints that WebCrumbs could implement to align with WordPress. Your list can be simple, no need for any tech jargon.

3. **Save it**: Place your Markdown file in the `/research` directory in our GitHub repository.

That's it! By doing this, you're contributing valuable information that will help shape WebCrumbs' compatibility with WordPress. We're starting fresh, and every contribution counts.

Ready to take on the task? [Here's your portal to the WebCrumbs GitHub repo. Go make history.](https://github.com/webcrumbs-community/webcrumbs)

**Comment by iceTmZz** [comment]
Hey, since no one seems to be working on this one, I would like to be assigned

**Comment by webcrumbs-community** [comment]
Hello there, @iceTmZz! Welcome to the community. My suggestion for this is to start with small steps and looking at Wordpress API for inspiration! 🍀

**Comment by iceTmZz** [comment]
> @iceTmZz I realized the description of this issue was too superficial. I made it longer. See if it helps and let me know if you need anything. Cheers!

This might be sophisticated for me cause I am not used to complex projects. But as per my understanding, I should be documenting Wordpress endpoints similar to Webcrumbs API, targeted to help users transition from Wordpress to Webcrumb right?

**Comment by aizhuxue007** [comment]
@webcrumbs-community Hello I would like this to be assigned to me. Thank you!

**Comment by webcrumbs-community** [comment]
Great, @aizhuxue007! Let us know if you need anything

**Comment by aizhuxue007** [comment]
@webcrumbs-community Thanks for assigning this to me. Is there a due date for this issue, if so when would it be do for me?

**Comment by webcrumbs-community** [comment]
@aizhuxue007 You're welcome, mate. I thank you for joining the team. This issue is definitely important, but we're not setting deadlines for now, so take your time. A weekly update would be good. Cheers!

**Comment by webcrumbs-community** [comment]
How is it going, do you need any help from the community? @aizhuxue007

**Comment by aizhuxue007** [comment]
@aizhuxue007 Hello I think i already sent a PR that was already merged for this issue. I'm open to feedback for it. 

Also another contributor @aditya4196 suggested using a tool called Swagger to write better markdowns for API endpoints. It could be useful down the road for an issue like this.

Here's the link: https://swagger.io/docs/

Thanks a lot!

**Comment by webcrumbs-community** [comment]
Apologies! I guess I was in a hurry to close as many issues as possible and let it slip. My mistake. Yes, I've seen it and it looks great. It will help us with compatibility. And yes, OpenAPI is a good practice. Thanks again! I'm closing this now. ❤️
