### ISSUE TITLE
What is going on ?

### ISSUE THREAD

**Issue by dshaw0004** [webcrumbs-community/webcrumbs#98]
![landing](https://github.com/webcrumbs-community/webcrumbs/assets/114005178/d74208bb-65dc-4d14-bd8d-2ad1c19b03a5)
error in landing page

![Screenshot (284)](https://github.com/webcrumbs-community/webcrumbs/assets/114005178/8575b073-4e49-46e3-bf46-b337b4376ba6)
error in admin page

I was busy in my job lately so I was not able to follow up the repo.
When I try to contribute to it today (27 oct 2023) I am facing these issues.

@webcrumbs-community

**Comment by webcrumbs-community** [comment]
Hi, @dshaw0004! 

Thanks for raising the concern. 

For landing, you're right. It's not compiling. In any case, we've been working on the lading in issue #39, and you'll see a draft [here](https://anysite-2dd7be.webflow.io/).

For admin, my suggestion is:

1. `git pull` - if you have problems with this, clone the repo again
2. `cd ..admin`
3. `npm i`
4. `npm run dev`
5. See if it works

Please let me know.
Cheers!

**Comment by dshaw0004** [comment]
I was having issue in `git pull` so I deleted my local repo then freshly clone your repo again
